---

   - name: GET request - Polling current votes.
     uri: url=http://ec2-52-29-73-231.eu-central-1.compute.amazonaws.com:8000/polls/1/results/ return_content=yes
     register: webpage
   
   - name: Debug - GET request.
     debug:
       msg: "{{ webpage.content }}"

   - name: POST request - Voting for 1st option. 
     uri:
       url: http://ec2-52-29-73-231.eu-central-1.compute.amazonaws.com:8000/polls/1/vote/
       method: POST
       status_code: 302
       HEADER_Content-Type: "application/x-www-form-urlencoded"
       HEADER_Cookie: "csrftoken=caEPKEXXcKsjJk08z57HppZVzr5kcJxm; sessionid=rry1fim3a7f4opxu83osrxyhruey441b"
       body: "csrfmiddlewaretoken=caEPKEXXcKsjJk08z57HppZVzr5kcJxm&choice=1"

   - name: POST request - Voting for 2nd option.
     uri:
       url: http://ec2-52-29-73-231.eu-central-1.compute.amazonaws.com:8000/polls/1/vote/
       method: POST
       status_code: 302
       HEADER_Content-Type: "application/x-www-form-urlencoded"
       HEADER_Cookie: "csrftoken=caEPKEXXcKsjJk08z57HppZVzr5kcJxm; sessionid=rry1fim3a7f4opxu
83osrxyhruey441b"
       body: "csrfmiddlewaretoken=caEPKEXXcKsjJk08z57HppZVzr5kcJxm&choice=2"

   - name: GET request - checking votes results.
     uri: url=http://ec2-52-29-73-231.eu-central-1.compute.amazonaws.com:8000/polls/1/results/ return_content=yes
     register: webpage_after

   - name: Debug - GET request.
     debug:
       msg: "{{ webpage_after.content }}"

