---

   - fail: msg="This play requires 'project_name' set via vars or as --extra-vars."
     when: (project_name == '')

   - name: Ensuring destination folder is present.
     file: path="{{ destination }}" state=directory recurse=yes

   - include: cleanup.yml
     when: (runcleaning == 'yes')
   
   - include: run.yml
     when: (runproject == 'yes')
