---
   
   - name: Cloning repository to destination path.
     git: repo={{ git_repo }} dest={{ destination }} clone=yes update=yes

   - name: Starting Django development server.
     shell: chdir="{{ destination }}{{ project_name }}" {{ item }}
     with_items:
       "nohup python manage.py runserver 0.0.0.0:8000 &"
